name: release-packages

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  get-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.ref_name }}

      - name: Extract version
        id: version
        run: |
          VERSION=$(grep 'PKG_VERSION:=' ./Makefile | awk -F '=' '{print $2}')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "New Version: ${VERSION}"

  release:
    name: ${{ matrix.arch }}-${{ matrix.branch }} release
    needs: get-version
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        branch:
          - openwrt-24.10
          - SNAPSHOT

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Preparing Build Environment
        run: |
          echo "Setting up the build environment for ${{ matrix.arch }}-${{ matrix.branch }}"
          mkdir -p feeds/luci-theme-rtawrt artifacts
          rsync -av --exclude='feeds/' --exclude='artifacts/' ./ ./feeds/luci-theme-rtawrt/
          echo "Build environment setup complete."

      - name: build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feeds
          PACKAGES: luci-theme-rtawrt
          NO_REFRESH_CHECK: true

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ needs.get-version.outputs.version }}"
          files: |
            ${{ github.workspace }}/artifacts/bin/packages/*/action/luci-theme-rtawrt_*
          generate_release_notes: true

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: luci-theme-rtawrt
          path: ${{ github.workspace }}/artifacts/bin/packages/*/action/luci-theme-rtawrt_*
