name: Build and Release Theme

on:
  workflow_dispatch:

jobs:
  build_ipk:
    name: Build Theme RTA-WRT
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

      - name: Extract version
        id: version
        run: |
          VERSION=$(grep 'PKG_VERSION:=' ./Makefile | awk -F '=' '{print $2}')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "New Version: ${VERSION}"

      - name: Preparing Build Environment
        run: |
          echo "Setting up the build environment..."
          mkdir -p feeds/luci-theme-rtawrt artifacts
          rsync -av --exclude='feeds/' --exclude='artifacts/' ./ ./feeds/luci-theme-rtawrt/
          echo "Build environment setup complete."

      - name: Building Luci Theme RTA-WRT
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: x86_64-23.05.5
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feeds
          PACKAGES: luci-theme-rtawrt
          NO_SHFMT_CHECK: 1

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/artifacts/bin/packages/*/action/luci-theme-rtawrt_*.ipk
          overwrite: true
          tag: latest
          file_glob: true
          body: |
            This is a new release of RTA-WRT theme.
